# Express Server Configuration

# HTTP server port (using your actual port)
port: 2100

# Public URL for accessing UGC content
# Set to your actual server address
public_url: "http://localhost:2100"

# Content directories
content:
  # Base directory for user-generated content
  # Changed to match your file system structure
  ugc_dir: "../ugc"

  # URL path prefix for UGC files
  ugc_path: "/ugc"

# Security settings
security:
  # Maximum allowed upload size in MB
  max_upload_size: 10

  # Content types allowed
  allowed_mime_types:
    - "image/jpeg"
    - "image/jpg"
    - "image/png"
    - "image/gif"
    - "image/webp"